/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socketdemo;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;

/**
 *
 * @author Admin
 */
public class ChatPanel extends javax.swing.JPanel {
    private Socket socket;
    private BufferedReader bf = null;
    private DataOutputStream os = null;
    private OutputThread t = null;
    private String sender;
    private String receiver;

    public ChatPanel(Socket socket, String sender, String receiver) {
        initComponents();
        try {
            this.socket = socket;
            this.sender = sender;
            this.receiver = receiver;
            
            bf = new BufferedReader(new InputStreamReader(socket.getInputStream())); // nhận dữ liệu
            os = new DataOutputStream(socket.getOutputStream()); // chuyển dữ liệu
            t = new OutputThread(socket, getTxtMessages(), sender, receiver);
            t.start();
        } catch (Exception e) {
        }
        
    }
    
    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        txtMessages.setColumns(20);
        txtMessages.setRows(5);
        jScrollPane1.setViewportView(txtMessages);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new java.awt.GridLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 50));

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane2.setViewportView(txtMessage);

        jPanel1.add(jScrollPane2);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // kiểm tra xem có đoạn tin nhắn gì không
        if (getTxtMessage().getText().trim().length()==0) return;
        try { // nếu có thì gửi đoạn tin nhắn 
            getOs().writeBytes(getTxtMessage().getText()); // chuyển chuỗi thành dãy byte để chuyển đi
            getOs().write(13); // ký tự xuống hàng
            getOs().write(10); // thụt zo đầu dòng
            getOs().flush(); // đẩy dãy dữ liệu đi
            this.getTxtMessages().append("\n" + getSender() + ": " + getTxtMessage().getText()); // show lên khung chat
            getTxtMessage().setText(""); // xóa dữ liệu khung tin nhắn
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextArea txtMessages;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the socket
     */
    public Socket getSocket() {
        return socket;
    }

    /**
     * @param socket the socket to set
     */
    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    /**
     * @return the bf
     */
    public BufferedReader getBf() {
        return bf;
    }

    /**
     * @param bf the bf to set
     */
    public void setBf(BufferedReader bf) {
        this.bf = bf;
    }

    /**
     * @return the os
     */
    public DataOutputStream getOs() {
        return os;
    }

    /**
     * @param os the os to set
     */
    public void setOs(DataOutputStream os) {
        this.os = os;
    }

    /**
     * @return the t
     */
    public OutputThread getT() {
        return t;
    }

    /**
     * @param t the t to set
     */
    public void setT(OutputThread t) {
        this.t = t;
    }

    /**
     * @return the sender
     */
    public String getSender() {
        return sender;
    }

    /**
     * @param sender the sender to set
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * @return the receiver
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * @param receiver the receiver to set
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * @return the btnSend
     */
    public javax.swing.JButton getBtnSend() {
        return btnSend;
    }

    /**
     * @param btnSend the btnSend to set
     */
    public void setBtnSend(javax.swing.JButton btnSend) {
        this.btnSend = btnSend;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @return the txtMessage
     */
    public javax.swing.JTextArea getTxtMessage() {
        return txtMessage;
    }

    /**
     * @param txtMessage the txtMessage to set
     */
    public void setTxtMessage(javax.swing.JTextArea txtMessage) {
        this.txtMessage = txtMessage;
    }

    /**
     * @return the txtMessages
     */
    public javax.swing.JTextArea getTxtMessages() {
        return txtMessages;
    }

    /**
     * @param txtMessages the txtMessages to set
     */
    public void setTxtMessages(javax.swing.JTextArea txtMessages) {
        this.txtMessages = txtMessages;
    }
}
