/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Admin
 */
public class QLNS extends javax.swing.JFrame {

    /**
     * Creates new form QLNS
     */
    public QLNS() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.mnuDX.enable(false);
        this.mnuDN.enable(true);
        this.mnuHoaDon.enable(false);
        this.mnuLoaiSach.enable(false);
        this.mnuPN.enable(false);
        this.mnuSach.enable(false);
        this.mnuDX.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuHT = new javax.swing.JMenu();
        mnuDN = new javax.swing.JMenuItem();
        mnuDX = new javax.swing.JMenuItem();
        mnuThoat = new javax.swing.JMenuItem();
        mnuQL = new javax.swing.JMenu();
        mnuLoaiSach = new javax.swing.JMenuItem();
        mnuSach = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenuItem();
        mnuPN = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuHT.setMnemonic('f');
        mnuHT.setText("Hệ Thống");

        mnuDN.setMnemonic('o');
        mnuDN.setText("Đăng nhập");
        mnuDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDNActionPerformed(evt);
            }
        });
        mnuHT.add(mnuDN);

        mnuDX.setMnemonic('s');
        mnuDX.setText("Đăng xuất");
        mnuHT.add(mnuDX);

        mnuThoat.setMnemonic('a');
        mnuThoat.setText("Thoát");
        mnuHT.add(mnuThoat);

        menuBar.add(mnuHT);

        mnuQL.setMnemonic('e');
        mnuQL.setText("Quản Lý");

        mnuLoaiSach.setMnemonic('t');
        mnuLoaiSach.setText("Loại sách");
        mnuLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoaiSachActionPerformed(evt);
            }
        });
        mnuQL.add(mnuLoaiSach);

        mnuSach.setMnemonic('y');
        mnuSach.setText("Sách");
        mnuSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSachActionPerformed(evt);
            }
        });
        mnuQL.add(mnuSach);

        mnuHoaDon.setMnemonic('p');
        mnuHoaDon.setText("Hóa đơn");
        mnuQL.add(mnuHoaDon);

        mnuPN.setMnemonic('d');
        mnuPN.setText("Phiếu nhập sách");
        mnuQL.add(mnuPN);

        menuBar.add(mnuQL);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Hướng Dẫn");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSachActionPerformed

    private void mnuDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDNActionPerformed
        DangNhap dn = new DangNhap(this, rootPaneCheckingEnabled);
        dn.setVisible(true);
        if(dn.isKqDN())
        {
            this.mnuDX.setEnabled(true);
            this.mnuDN.setEnabled(false);
            this.mnuHoaDon.setEnabled(true);
            this.mnuLoaiSach.setEnabled(true);
            this.mnuPN.setEnabled(true);
            this.mnuSach.setEnabled(true);
            this.mnuDX.setEnabled(true);
        }
    }//GEN-LAST:event_mnuDNActionPerformed

    private void mnuLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoaiSachActionPerformed
        LoaiSach ls = new LoaiSach();
        ls.setVisible(true);
        this.desktopPane.add(ls);
    }//GEN-LAST:event_mnuLoaiSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuDN;
    private javax.swing.JMenuItem mnuDX;
    private javax.swing.JMenu mnuHT;
    private javax.swing.JMenuItem mnuHoaDon;
    private javax.swing.JMenuItem mnuLoaiSach;
    private javax.swing.JMenuItem mnuPN;
    private javax.swing.JMenu mnuQL;
    private javax.swing.JMenuItem mnuSach;
    private javax.swing.JMenuItem mnuThoat;
    // End of variables declaration//GEN-END:variables

}
