/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.LoaiSachDAO;
import dao.SachDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.LoaiSach;
import pojo.Sach;

/**
 *
 * @author Admin
 */
public class SachFrame extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    /**
     * Creates new form Sach
     */
    public SachFrame() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();
        jComboBox2.setVisible(false);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTacGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNamxb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMoTa = new javax.swing.JTextField();
        btnE = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Tác giả", "Năm XB", "Thể loại", "Mô tả"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 449, 133);

        jLabel1.setText("Tên:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 160, 30, 14);
        getContentPane().add(tfTen);
        tfTen.setBounds(118, 155, 277, 30);

        jLabel2.setText("Tác Giả:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 210, 50, 14);
        getContentPane().add(tfTacGia);
        tfTacGia.setBounds(120, 200, 277, 30);

        jLabel3.setText("Thể loại:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 250, 60, 14);

        tfType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTypeFocusGained(evt);
            }
        });
        getContentPane().add(tfType);
        tfType.setBounds(120, 240, 277, 30);

        jLabel4.setText("Năm xb:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 290, 60, 14);
        getContentPane().add(tfNamxb);
        tfNamxb.setBounds(120, 280, 275, 30);

        jLabel6.setText("Mô tả:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 330, 50, 14);
        getContentPane().add(tfMoTa);
        tfMoTa.setBounds(120, 320, 273, 30);

        btnE.setText("Thoát");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        getContentPane().add(btnE);
        btnE.setBounds(320, 370, 70, 23);

        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel);
        btnDel.setBounds(240, 370, 70, 23);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua);
        btnSua.setBounds(160, 370, 70, 23);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(80, 370, 70, 23);

        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox2FocusLost(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(120, 240, 275, 30);

        setBounds(0, 0, 485, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        tfType.setVisible(true);
        jComboBox2.setVisible(false);
        tfTen.setText((String) dtm.getValueAt(row, 1));
        tfTacGia.setText((String) dtm.getValueAt(row, 2));
        tfNamxb.setText(dtm.getValueAt(row, 3) + "");
        tfType.setText((String) dtm.getValueAt(row, 4));
        tfMoTa.setText((String) dtm.getValueAt(row, 5));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        tfMoTa.setText("");
        tfNamxb.setText("");
        tfTacGia.setText("");
        tfTen.setText("");
        tfType.setText("");
        tfType.setVisible(false);
        jComboBox2.setVisible(true);
        ArrayList<LoaiSach> lstLS = LoaiSachDAO.showData();
        lstLS.forEach(loaiSach ->{
            jComboBox2.addItem(loaiSach.getStrTen());
        });
        tfTen.requestFocus(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int row = jTable1.getSelectedRow();
        Sach s = new Sach();
        s.setMa(Integer.parseInt(dtm.getValueAt(row, 0).toString()));
        int ck = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (ck==JOptionPane.YES_OPTION)
            if (SachDAO.delSach(s)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                loadData();
            }
            else JOptionPane.showMessageDialog(this, "Xóa thất bại. Vui lòng thử lại", "Thông Báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            int count = SachDAO.countSach();
            int n = 0;
            Sach s = new Sach();
            if (SachDAO.bCheckTen(tfTen.getText())) {
                int ck = JOptionPane.showConfirmDialog(this, "Tên sách đã tồn tại bạn có muốn cập nhật hay không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (ck == JOptionPane.YES_OPTION) {
                    s.setTieuDe(tfTen.getText());
                    s.setMoTa(tfMoTa.getText());
                    s.setNamXB(Integer.parseInt(tfNamxb.getText()));
                    s.setTacGia(tfTacGia.getText());
                    s.setTheLoai(tfType.getText());
                    
                    int row = jTable1.getSelectedRow();
                    s.setMa((int) dtm.getValueAt(row, 0));
                    
                    n = SachDAO.udSach(s)?1:0;
                }
            }else {
                s.setTieuDe(tfTen.getText());
                s.setMoTa(tfMoTa.getText());
                s.setNamXB(Integer.parseInt(tfNamxb.getText()));
                s.setTacGia(tfTacGia.getText());
                s.setTheLoai(tfType.getText());
                s.setMa(count+1);
                n = SachDAO.insertSach(s)?1:0;
            }
            if (n>0) {
                loadData();
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin sách thành công", "thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            else JOptionPane.showMessageDialog(this, "Cập nhật thông tin sách Thất bại vui lòng thử lại", "thông báo", JOptionPane.WARNING_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi. Vui lòng thử lại\n"+e.getMessage(), "thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tfTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTypeFocusGained
        tfType.setVisible(false);
        jComboBox2.setVisible(true);
        ArrayList<LoaiSach> lstLS = LoaiSachDAO.showData();
        lstLS.forEach(loaiSach ->{
            jComboBox2.addItem(loaiSach.getStrTen());
        });
        jComboBox2.setSelectedItem(tfType.getText());
    }//GEN-LAST:event_tfTypeFocusGained

    private void jComboBox2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusLost
        tfType.setText(jComboBox2.getSelectedItem().toString());
        tfType.setVisible(true);
        jComboBox2.removeAllItems();
        jComboBox2.setVisible(false);
    }//GEN-LAST:event_jComboBox2FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfMoTa;
    private javax.swing.JTextField tfNamxb;
    private javax.swing.JTextField tfTacGia;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfType;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        jComboBox2.removeAllItems();
        tfType.setVisible(true);
        jComboBox2.setVisible(false);
        dtm.setRowCount(0);
        ArrayList<Sach> arS = SachDAO.showLst();
        arS.forEach(sach -> {
            Vector<Object> v = new Vector<Object>();
            v.add(sach.getMa());
            v.add(sach.getTieuDe());
            v.add(sach.getTacGia());
            v.add(sach.getNamXB());
            v.add(sach.getTheLoai());
            v.add(sach.getMoTa());
            dtm.addRow(v);
        });
    }
}
